### PR TITLE
update to latest LTS and fix jelly compile issue

### PR DESCRIPTION
**Pull request by abedwardsw**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Sorry, but I'm against it. This change drops the support of all previous releases without a real reason
:-1: regarding the merge

**Comment by oleg-nenashev** [comment]
@escoem Is the plugin maintainer, so he is the best person to kick-off the release

**Comment by abedwardsw** [comment]
@oleg-nenashev there are 3 commits on master waiting for a release for about 2 years now.   I don't think @escoem is maintaining this plugin anymore.   There are also 4-5 pull requests which seem valid waiting to be merged.   I would be happy to give a hand getting these merged and released if someone gives me the rights.

**Comment by escoem** [comment]
hi @abedwardsw I've asked for maintain this plugin few time ago. Also @keilw ask for it and is helping. All we need is time to order the issues and the PRs. We will release it in few days. Thanks for your patient.

**Comment by keilw** [comment]
Sure, happy to help. What's the best way here. raising pull-requests from your own forks?

**Comment by escoem** [comment]
First release the master and after that PR from forks with jira issue. That's my opinion.

Tomorrow I will release the master.

**Pull request closed without merging**
