### PR TITLE
removed import javax.xml.bind

### PR DESCRIPTION
**Pull request by mrinal1209**
@martinda please check the following issue https://issues.jenkins-ci.org/browse/JENKINS-55957
is resolved or not .

### CODE REVIEW

**Comment by batmat** [comment]
Heh, thanks.

For reference, this import was unused since https://github.com/jenkinsci/job-import-plugin/commit/8f826a684ba0969697d2a92a6f448aef8f03b66c#diff-5a2b372f3c05a41772f214e4a1c19a42L55

**Comment by batmat** [comment]
ping @jenkinsci/java11-support FYI

**Comment by batmat** [comment]
Gentle ping @escoem as current maintainer. Thanks :)

**Comment by batmat** [comment]
@escoem @daniel-beck are you maintainers for this plugin? (asking because you were the last releasers).

Thanks

**Comment by daniel-beck** [comment]
Emilio maintains it, I staged a security fix.

**Pull request merged**
