### PR TITLE
JENKINS-35983 - Add support to job import jobs in folders

### PR DESCRIPTION
**Pull request by Evildethow**
@reviewbybees cc @escoem 

Looks like this duplicates effort in https://github.com/jenkinsci/job-import-plugin/pull/4 :(

I actually like [this PR](https://github.com/jenkinsci/job-import-plugin/pull/4) better as it seems the author has updated the UI to allow being selective about child jobs in folders, which I didn't bother with. The only thing my PR has over this PR is that it adds tests and a mini test framework for stubbing the remote Jenkins, which can be re-used.
## Notes for release
- Jenkins base version bumped `1.580 -> 1.609.1` (required for `cloudbees-folder` dependency)
- Transient dependency `cloudbees-folder:5.12` added

### CODE REVIEW

**Comment by kuisathaverat** [comment]
🐝 LGTM

**Comment by Evildethow** [comment]
@reviewbybees can I get another bee to look at this?

**Comment by escoem** [comment]
@Evildethow I'm trying to merge both PR... I need some time to do it :-)

**Comment by escoem** [comment]
closed in favour of PR16

**Pull request closed without merging**
